services:
  - type: web
    name: betyard-ml-backend
    env: python
    buildCommand: "cp ml-backend/requirements.txt . && pip install -r requirements.txt"
    startCommand: "python ml-backend/app.py"
    plan: free
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /health